[build]
command = "npm i && npm run build && npm run bundle && npm run build:lambda && cd functions && npm i"
base = ""
functions = "functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
